fix: keep the query params when the webhook is called
gravitee-io/gravitee-notifier-webhook pull request #25
Opened 2023-07-04 07:17 UTC by aurelien-pacaud

**Issue**

https://gravitee.atlassian.net/browse/AE-67

**Description**

If the URL of the webhook contains query params, these query params are kept and sent

2023-07-04 07:30 UTC, jhaeyaert requested changes

2023-07-04 07:30 UTC, jhaeyaert commented on src/main/java/io/gravitee/notifier/webhook/WebhookNotifier.java
> +            .setURI(target.getPath() + (target.getQuery() != null ? target.getQuery() : ""))
The query param delimiter is missing. 
I know it can be time-consuming (and there is currently no test at all), but could you find time to add a simple unit test to validate the nominal case 🙏 ?

2023-07-05 13:55 UTC, aurelien-pacaud commented on src/main/java/io/gravitee/notifier/webhook/WebhookNotifier.java
> +            .setURI(target.getPath() + (target.getQuery() != null ? target.getQuery() : ""))
Tests added and I fixed the issue with the query delimiter.

2023-07-05 14:03 UTC, jhaeyaert approved these changes

2023-07-05 14:16 UTC, merged

2023-07-05 14:19 UTC, graviteeio commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on:
- `1.1.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-notifier-webhook/releases/tag/1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: